Repository sherpa/sherpa, pull requests merged in 2018-06, with the labels that each got.

#467 Add simple MacOS Travis job
  .travis.yml
  travis/setup_conda.sh
  travis/setup_xspec_ds9.sh
  travis/test.sh
Labels: area:build

#461 Mention Python 3.6 in the README (fix #453)
  README.md
Labels: area:docs

#462 Remove pyfits support (address #460)
  README.md
  sherpa/astro/io/__init__.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/utils/smoke.py
  sherpa/utils/testing.py
Labels: area:build, area:code

#463 Add missing RoutG alias for XSlaor (fix #443)
  sherpa/astro/xspec/__init__.py
Labels: area:code, dep:xspec
