Repository sherpa/sherpa, pull requests merged in 2019-11, with the labels that each got.

#667 improve matplotlib plot_fit plots (order of data and model)
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/plot/__init__.py
  sherpa/plot/pylab_backend.py
  sherpa/plot/tests/test_plot.py
  sherpa/plot/tests/test_pylab.py
Labels: area:code, dep:matplotlib, general:visualization

#698 Add warnings in documentation about masked arrays loaded into Sherpa
  sherpa/data.py
  sherpa/ui/utils.py
Labels: area:docs

#705 modelCacher1d needs to have a couple of deep instead of shallow copy()
  sherpa/astro/tests/test_cache.py
  sherpa/models/model.py
Labels: area:code, type:bug

#692 Allow users to override plot preferences when creating a plot
  docs/_examples/plots/index.py
  docs/_static/examples/user_model/data.png
  docs/_static/examples/user_model/intproj_c0_auto.png
  docs/_static/examples/user_model/intproj_c0_manual.png
  docs/_static/examples/user_model/model_data_before_fit.png
  docs/_static/examples/user_model/model_data_delchi.png
  docs/_static/examples/user_model/model_data_fit1.png
  docs/_static/examples/user_model/model_data_fit2.png
  docs/_static/examples/user_model/model_data_fit_all.png
  docs/_static/examples/user_model/model_data_myexp.png
  docs/_static/examples/user_model/model_data_reset.png
  docs/_static/examples/user_model/regproj_a_b_manual.png
  docs/_static/examples/user_model/regproj_offset_coeff_auto.png
  docs/_static/examples/user_model/regproj_offset_coeff_manual.png
  docs/_static/plots/dataplot_histogram.png
  docs/_static/plots/dataplot_histogram_overplot.png
  docs/_static/plots/fitplot_histogram.png
  docs/_static/plots/fitplot_histogram_after.png
  docs/_static/plots/intproj_histogram_pos.png
  docs/_static/plots/modelplot_histogram_overplot.png
  docs/_static/plots/settings_dataplot_combined.png
  docs/_static/plots/settings_dataplot_ylog.png
  docs/examples/simple_interpolation.rst
  docs/examples/simple_user_model.rst
  docs/plots/index.rst
  docs/ui/index.rst
  sherpa/astro/plot.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
  sherpa/plot/__init__.py
  sherpa/ui/utils.py
Labels: general:visualization, type:enhancement

#710 Add warning about masked array to sherpa.astro.ui.load_arrays
  sherpa/astro/ui/utils.py
Labels: area:docs
