Repository sherpa/sherpa, pull requests merged in 2020-04, with the labels that each got.

#745 ensure that min/max limits are applied to linked parameters before use
  sherpa/astro/xspec/tests/test_xspec_unit.py
  sherpa/models/parameter.py
  sherpa/models/tests/test_parameter.py
Labels: area:code, type:bug

#732 Remove unused Python 2.7 compatibility code
  sherpa/astro/io/crates_backend.py
  sherpa/astro/utils/src/_region.cc
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/src/_xspec.cc
  sherpa/image/DS9.py
  sherpa/include/sherpa/extension.hh
  sherpa/include/sherpa/integration.hh
  sherpa/include/sherpa/model_extension.hh
  sherpa/models/tests/test_model.py
  sherpa/models/tests/test_parameter.py
  sherpa/sim/mh.py
  sherpa/utils/__init__.py
  sherpa/utils/src/_psf.cc
  sherpa/utils/src/integration.cc
Labels: area:code

#756 calculate_photon_flux/calculate_energy_flux fix and improvement
  sherpa/astro/tests/test_astro.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/utils.py
  sherpa/astro/utils/__init__.py
  sherpa/astro/utils/tests/test_astro_utils.py
  sherpa/astro/utils/tests/test_astro_utils_unit.py
  sherpa/utils/__init__.py
  sherpa/utils/tests/test_utils.py
Labels: area:code, area:tests, type:bug, type:enhancement

#781 Docs: fix typo in docstring for calc_kcorr
  sherpa/astro/ui/utils.py
Labels: area:docs

#794 Get linux libgfortran from conda-forge
  .travis.yml
  travis/setup_conda.sh
  travis/setup_xspec_ds9.sh
Labels: area:tests
