Repository sherpa/sherpa, pull requests merged in 2020-09, with the labels that each got.

#924 Updated to ignore the .vscode directory
  .gitignore
Labels: area:other, note: easy review

#928 Tests: change test_astro_sim.py::test_pragbayes_pcaarf_limits
  sherpa/astro/sim/tests/test_astro_sim.py
  sherpa/conftest.py
Labels: area:tests, note: easy review

#882 Add tests of background handling
  sherpa/astro/ui/tests/test_astro_ui_background.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/conftest.py
  sherpa/stats/tests/test_wstat.py
Labels: area:tests, note: easy review

#812 Add unsubtract and ungroup to datastack
  sherpa/astro/datastack/ds.py
  sherpa/astro/datastack/tests/test_datastack.py
Labels: area:code, note: easy review, type:enhancement

#791 Fix ignore/notice error-ing out when all bins have been set bad #790
  sherpa/astro/data.py
  sherpa/astro/ui/tests/test_astro_ui.py
Labels: area:code, area:tests, type:bug

#940 Minor documentation improvements
  sherpa/astro/xspec/__init__.py
  sherpa/ui/utils.py
Labels: area:docs, note: easy review

#918 fix an issue with PHA filtering that affects plot_model
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/utils/__init__.py
  sherpa/utils/tests/test_utils.py
Labels: area: grouping, area:code, type:bug

#884 Move logic from ui layer to DataPHA class: background responses (fix #879, #880)
  sherpa/astro/background.py
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/ui/tests/test_astro_ui_background.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/utils.py
  sherpa/ui/tests/test_ui_unit.py
  sherpa/ui/utils.py
  sherpa/utils/err.py
Labels: area:code, area:tests

#935 Remove the RTD Travis build
  .travis.yml
Labels: area:build, note: easy review

#939 Docs: note XSPEC convolution models are new in 4.12.2
  sherpa/astro/xspec/__init__.py
Labels: area:docs, note: easy review

#740 resample_data: when the error range on a bin includes -1 and no-longer restrict sampling to +/-1 sigma
  sherpa/astro/ui/utils.py
  sherpa/sim/__init__.py
  sherpa/sim/tests/test_asymmetric.py
Labels: area:code, general:statistics, type:bug

#922 channel settings with grouped PHA data and model plotting
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_instrument.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
Labels: area: grouping, area:code, type:bug

#942 Tests: support Crates as well as the AstroPy backend
  sherpa/astro/ui/tests/test_astro_ui_background.py
Labels: area:tests, note: easy review

#803 Updates to sampling of energy and photon fluxes: bug fixes and calculate unabsorbed components
  sherpa/astro/flux.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
  sherpa/sim/sample.py
  sherpa/ui/utils.py
Labels: area:code, area:docs, area:tests, type:bug, type:enhancement
