Repository sherpa/sherpa, pull requests merged in 2020-10, with the labels that each got.

#950 Documentation fixes
  docs/mcmc/sim.rst
  docs/ui/sherpa_astro_ui.rst
  docs/ui/sherpa_ui.rst
  sherpa/astro/data.py
  sherpa/astro/ui/utils.py
  sherpa/astro/xspec/__init__.py
  sherpa/sim/__init__.py
  sherpa/ui/utils.py
Labels: area:docs, note: easy review

#888 Support vector backscales and bugfix for background modelling
  docs/evaluation/astro_background.rst
  sherpa/astro/background.py
  sherpa/astro/data.py
  sherpa/astro/instrument.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_background.py
  sherpa/astro/ui/tests/test_astro_ui_utils_simulation.py
  sherpa/astro/ui/utils.py
  sherpa/models/model.py
  sherpa/models/tests/test_model.py
  sherpa/ui/utils.py
Labels: area:code, area:tests, type:bug

#953 docstring fixes
  sherpa/astro/models/__init__.py
  sherpa/astro/ui/utils.py
  sherpa/astro/xspec/__init__.py
  sherpa/ui/utils.py
Labels: area:docs, note: easy review

#906 Improve and add support for histogram plots
  docs/_examples/developer/ui_plot.py
  docs/_static/developer/ui_plot_fit_basic.png
  docs/_static/developer/ui_plot_fit_manual.png
  docs/developer/index.rst
  docs/plots/astroplot.rst
  docs/plots/plot.rst
  sherpa/astro/plot.py
  sherpa/astro/tests/test_astro_plot.py
  sherpa/astro/ui/tests/test_astro_ui_background.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
  sherpa/conftest.py
  sherpa/plot/__init__.py
  sherpa/plot/pylab_backend.py
  sherpa/plot/tests/test_plot.py
  sherpa/ui/tests/test_plot_pvalue.py
  sherpa/ui/tests/test_ui.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
Labels: area:code, dep:matplotlib, general:visualization, type:bug, type:enhancement

#955 Test FIXUP issue with merge of #906
  sherpa/astro/ui/tests/test_astro_ui_background.py
Labels: area:tests, note: easy review, priority:blocker

#631 Add HTML representations of common classes for IPython display (fix #345)
  MANIFEST.in
  notebooks/SherpaQuickStart.ipynb
  setup.py
  sherpa/astro/data.py
  sherpa/astro/io/__init__.py
  sherpa/astro/tests/test_astro_data_notebook.py
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/conftest.py
  sherpa/data.py
  sherpa/fit.py
  sherpa/models/model.py
  sherpa/models/parameter.py
  sherpa/models/tests/test_model_notebook.py
  sherpa/plot/__init__.py
  sherpa/plot/dummy_backend.py
  sherpa/plot/pylab_backend.py
  sherpa/plot/tests/test_plot_notebook.py
  sherpa/static/css/style.css
  sherpa/tests/test_data_notebook.py
  sherpa/tests/test_fit_notebook.py
  sherpa/utils/formatting.py
Labels: area:code, general:visualization, type:enhancement

#957 Docs: include the example notebook in the RTD pages
  .gitignore
  MANIFEST.in
  docs/conf.py
  docs/environment.yml
  docs/index.rst
  docs/rtd-pip-requirements
  docs/ui/index.rst
  notebooks/nbmapping.dat
Labels: area:docs, note: easy review

#931 Update Data1DInt / DataPHA data plots to use the histogram plot style
  sherpa/astro/plot.py
  sherpa/astro/tests/test_astro_plot.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/utils.py
  sherpa/plot/__init__.py
  sherpa/plot/pylab_backend.py
  sherpa/plot/tests/test_plot.py
  sherpa/plot/tests/test_pylab.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
Labels: area:code, type:enhancement

#858 Minor documentation improvements to ReadTheDocs
  docs/_examples/evaluation/examples/pharesponses.py
  docs/_static/evaluation/pha_data.png
  docs/_static/evaluation/pha_data_compare.png
  docs/_static/evaluation/pha_data_manual.png
  docs/_static/evaluation/pha_data_wave.png
  docs/_static/evaluation/pha_eval_model_to_fit.png
  docs/_static/evaluation/pha_fullmodel_fit.png
  docs/_static/evaluation/pha_fullmodel_manual.png
  docs/_static/evaluation/pha_fullmodel_model.png
  docs/_static/evaluation/pha_model_energy.png
  docs/_static/evaluation/rspmodelnopha_channel.png
  docs/_static/evaluation/rspmodelnopha_energy.png
  docs/_static/evaluation/rspmodelpha_compare.png
  docs/evaluation/convolution.rst
  docs/evaluation/examples.rst
  docs/evaluation/regrid.rst
  docs/models/index.rst
Labels: area:docs

#944 Improve handling of the default id with PHA background datasets (fix issue #943)
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/utils.py
Labels: area:code, note: easy review, type:bug

#929 Support overplot option in plot_fit_xxx (issue #700)
  sherpa/conftest.py
  sherpa/plot/__init__.py
  sherpa/plot/pylab_backend.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
Labels: area:code, general:visualization, type:bug

#961 Update notebook support for Data1DInt/PHA data
  .gitignore
  docs/index.rst
  notebooks/NotebookSupport.ipynb
  notebooks/SherpaQuickStart.ipynb
  notebooks/nbmapping.dat
  sherpa/astro/data.py
  sherpa/data.py
  sherpa/tests/test_data_notebook.py
Labels: area:code, area:docs, type:enhancement

#963 Docs: note plot_fit_xxx overplot change and add info on notebook support
  docs/developer/index.rst
  docs/install.rst
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
Labels: area:docs, note: easy review

#964 Docs: avoid invalid escape sequence warning
  sherpa/stats/__init__.py
Labels: area:docs, note: easy review

#866 Add parameter-clipping strategy to routines that generate samples (fix #846)
  sherpa/astro/flux.py
  sherpa/astro/plot.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
  sherpa/sim/sample.py
  sherpa/sim/tests/test_sim.py
Labels: area:code, general:statistics, note:needs SDS testing, type:enhancement

#971 Docs: fix sphinx warnings
  sherpa/sim/sample.py
Labels: area:docs

#968 Fix 2d image filtering (fix #965)
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/utils/__init__.py
  sherpa/astro/utils/src/_region.cc
  sherpa/astro/utils/tests/test_region_unit.py
Labels: area:code, area:tests, type:bug

#969 Support Python 3.8 for MacOSX
  sherpa/optmethods/opt.py
  sherpa/sherpa-standalone.rc
  sherpa/sherpa.rc
  sherpa/utils/__init__.py
Labels: area:build, type:bug

#634 Added invitation for native software citation
  CITATION
  docs/developer/index.rst
  docs/install.rst
  docs/overview/sherpa.rst
  docs/overview/utilities.rst
  sherpa/__init__.py
  sherpa/astro/ui/utils.py
  sherpa/conftest.py
  sherpa/tests/test_sherpa.py
  sherpa/ui/utils.py
  sherpa/utils/__init__.py
Labels: area:code, area:docs, type:enhancement

#979 Improve plots of PHA data sets and models when the response grid is not ideal
  sherpa/astro/plot.py
  sherpa/astro/tests/test_astro_plot.py
Labels: area:code, general:visualization, note: easy review, type:bug

#984 Address set_xlog/ylog problems with DataPHA/Data1DInt classes (#981)
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
Labels: area:code, general:visualization, type:bug
