Repository sherpa/sherpa, pull requests merged in 2021-09, with the labels that each got.

#1264 Fix crash from grouping data using an unsupported method
  docs/_examples/data/pha.py
  docs/_examples/evaluation/examples/pharesponses.py
  docs/_static/data/pha_filtered.png
  docs/_static/data/pha_filtered_channel.png
  docs/_static/data/pha_grouping_comparison.png
  docs/_static/data/pha_initial.png
  docs/_static/evaluation/pha_data.png
  docs/_static/evaluation/pha_data_compare.png
  docs/_static/evaluation/pha_data_manual.png
  docs/_static/evaluation/pha_data_wave.png
  docs/_static/evaluation/pha_eval_model_to_fit.png
  docs/_static/evaluation/pha_fullmodel_fit.png
  docs/_static/evaluation/pha_fullmodel_manual.png
  docs/_static/evaluation/pha_fullmodel_model.png
  docs/_static/evaluation/pha_model_energy.png
  docs/data/pha.rst
  docs/evaluation/examples.rst
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_pha_scale.py
  sherpa/astro/utils/src/_utils.cc
  sherpa/astro/utils/tests/test_astro_utils_unit.py
  sherpa/include/sherpa/astro/utils.hh
  sherpa/plot/tests/test_plot.py
Labels: type:bug, area:c-code

#1260 Add a module to parse XSPEC model.dat and helper scripts
  MANIFEST.in
  docs/developer/index.rst
  docs/overview/astro_utils_xspec.rst
  docs/overview/utilities.rst
  scripts/add_xspec_model.py
  scripts/check_xspec_update.py
  scripts/create_xspec_extension
  sherpa/astro/utils/tests/test_astro_utils_xspec.py
  sherpa/astro/utils/xspec.py
Labels: type:enhancement, dep:xspec

#1170 Update Python and particularly number versions in documentation
  CONTRIBUTING.md
  README.md
  docs/index.rst
  docs/install.rst
  setup.py
Labels: area:build, area:docs, note: easy review

#1270 Cleanup setup
  setup.py
Labels: area:build

#1216 filter improvements for DataPHA and Data1DInt
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_swift_unit.py
  sherpa/astro/ui/tests/test_astro_supports_pha2.py
  sherpa/data.py
  sherpa/tests/test_data.py
  sherpa/utils/__init__.py
  sherpa/utils/tests/test_utils.py
Labels: area:science

#1250 Stop odd interaction between plot_model and PHA filters (Fix #1024)
  sherpa/astro/plot.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
Labels: type:bug, area:code, area: grouping, note: easy review

#1281 RTD: include parse_xspec_model_description
  docs/overview/astro_utils_xspec.rst
Labels: area:docs, note: easy review

#1282 Add Zenodo details for 4.13.1
  sherpa/__init__.py
Labels: area:docs, note: easy review

#1268 Doc: switch default sphinx role
  docs/conf.py
  sherpa/data.py
  sherpa/fit.py
  sherpa/io.py
  sherpa/stats/__init__.py
Labels: type:enhancement, area:docs

#1259 XSPEC parameter changes - you can change the hard limits of most XSPEC parameters
  sherpa/astro/tests/test_astro.py
  sherpa/astro/ui/serialize.py
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/astro/utils/smoke.py
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/tests/test_xspec.py
  sherpa/astro/xspec/tests/test_xspec_con.py
  sherpa/astro/xspec/tests/test_xspec_unit.py
Labels: type:enhancement, dep:xspec, note:needs SDS testing

#1223 XSPEC 12.12.0 support
  docs/developer/index.rst
  docs/indices.rst
  docs/install.rst
  docs/model_classes/xspec_model.rst
  helpers/xspec_config.py
  scripts/check_xspec_update.py
  sherpa/astro/ui/utils.py
  sherpa/astro/utils/tests/test_astro_utils_xspec.py
  sherpa/astro/utils/xspec.py
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/src/_xspec.cc
  sherpa/astro/xspec/tests/test_xspec.py
Labels: type:enhancement, priority:high, dep:xspec

#1219 Fix filter expressions
  docs/_examples/data/index.py
  docs/_examples/data/pha.py
  docs/_examples/developer/ui_plot.py
  docs/_examples/evaluation/convolution/psf1d.py
  docs/_examples/evaluation/convolution/psf2d.py
  docs/_static/data/data1d.png
  docs/_static/data/data1dint.png
  docs/_static/data/data_eval_model.png
  docs/_static/data/data_int_line_to_plot.png
  docs/_static/data/data_int_to_plot.png
  docs/_static/data/data_to_plot.png
  docs/_static/developer/ui_plot_fit_basic.png
  docs/_static/developer/ui_plot_fit_manual.png
  docs/_static/models/combine/convolution_psf2d_evaluate_conv.png
  docs/_static/models/combine/convolution_psf2d_evaluate_unconv.png
  docs/_static/plots/dataplot_histogram.png
  docs/_static/plots/dataplot_histogram_overplot.png
  docs/_static/plots/fitplot_histogram.png
  docs/_static/plots/fitplot_histogram_after.png
  docs/_static/plots/intproj_histogram_pos.png
  docs/_static/plots/modelplot_histogram_overplot.png
  docs/_static/plots/settings_dataplot_combined.png
  docs/_static/plots/settings_dataplot_ylog.png
  docs/data/index.rst
  docs/data/pha.rst
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_notebook.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_background.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/astro/ui/utils.py
  sherpa/data.py
  sherpa/tests/test_data.py
  sherpa/tests/test_data_notebook.py
  sherpa/ui/utils.py
  sherpa/utils/__init__.py
  sherpa/utils/tests/test_utils.py
Labels: area:science

#1288 Improve the PHA simulation documentation
  docs/evaluation/simulate.rst
Labels: area:docs

#1246 Image region filters are now specified correctly (Fix #1245)
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/utils/src/_region.cc
  sherpa/astro/utils/tests/test_region_unit.py
Labels: type:bug, priority:high, area:code, area:c-code

#1292 Update tests that were changed by #1246
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/ui/tests/test_serialize.py
Labels: priority:blocker, area:tests

#1290 Fix the string output of CDFPlot
  sherpa/plot/__init__.py
  sherpa/ui/tests/test_ui_plot.py
Labels: type:bug, area:docs, area:code

#1295 Update XSkerrconv model for #1275
  sherpa/astro/xspec/__init__.py
Labels: type:bug, area:code, dep:xspec

#1287 Remove C++ warning when compiling the pileup code
  sherpa/astro/utils/src/_pileup.cc
Labels: area:c-code

#1294 RTD: Fix some sphinx warnings (sherpa.models.regrid)
  sherpa/models/regrid.py
Labels: area:docs, note: easy review

#1106 The sample_flux routine now returns the correct information for the clip column
  sherpa/astro/flux.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/utils.py
Labels: type:enhancement, area:code

#1291 Comment: add link to the OSTI.GOV URL for the optimizing document
  sherpa/optmethods/tests/tstoptfct.hh
Labels: note: easy review, area:c-code

#1296 Document the neldermead reflect flag from #1285
  sherpa/optmethods/__init__.py
  sherpa/optmethods/optfcts.py
Labels: area:docs, note: easy review

#1293 RTD: add a "how to optimize a function" example
  docs/_examples/extra/optimize_function.py
  docs/_static/extra/normgauss1d-example.png
  docs/_static/extra/normgauss1d-trail.png
  docs/_static/extra/rosenbrock-surface.png
  docs/examples/fit_peaked_data.rst
  docs/extra/optimize_function.rst
  docs/index.rst
Labels: type:enhancement, area:docs

#1303 Updated Introductory Section of the MCMC page
  docs/mcmc/index.rst
  sherpa/sim/__init__.py
Labels: area:docs, note: easy review

#1308 Docs: fix get_filter examples
  sherpa/astro/data.py
  sherpa/ui/utils.py
Labels: area:docs, note: easy review
