Repository sherpa/sherpa, pull requests merged in 2021-08, with the labels that each got.

#1247 Allow save_all to work well with images with no filters (Fix #437)
  sherpa/astro/ui/serialize.py
  sherpa/astro/ui/tests/test_serialize.py
Labels: type:bug, area:code, note: easy review

#1215 Restrict the values used in PHA notice/filter calls
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_swift_unit.py
  sherpa/data.py
  sherpa/stats/tests/test_stats_unit.py
  sherpa/tests/test_data.py
  sherpa/tests/test_fit_unit.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/utils/tests/test_utils.py
Labels: type:enhancement, area:science

#1228 Fix three parameter names for XSPEC models
  sherpa/astro/xspec/__init__.py
  sherpa/models/model.py
Labels: type:bug, area:code, dep:xspec

#1248 Docs: note that set_stat can be sent a stats object
  sherpa/ui/utils.py
Labels: type:enhancement, area:docs, note: easy review

#1253 More numpy 1.20 warning fixes
  sherpa/astro/io/__init__.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/utils.py
  sherpa/ui/tests/test_ui_unit.py
  sherpa/ui/utils.py
Labels: priority:blocker, area:build, area:code, note: easy review

#1254 FIX: #1235 change XSPEC chatter to 10 from 0
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/src/_xspec.cc
Labels: dep:xspec, note:needs SDS testing, note: easy review, area:c-code

#1241 to get sherpa to run Apple M1 (arm)
  sherpa/utils/__init__.py
  sherpa/utils/src/cephes/const.c
  sherpa/utils/src/cephes/gamma.c
  sherpa/utils/src/cephes/ndtri.c
Labels: type:enhancement, area:build

#1031 Update fwhm calculation
  sherpa/astro/tests/test_astro.py
  sherpa/utils/__init__.py
  sherpa/utils/tests/test_utils_unit.py
Labels: type:question, type:bug, area:tests, area:code

#1244 Fix "unable to parse region string: None" errors (issue #1214)
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/ui/utils.py
  sherpa/instrument.py
  sherpa/ui/tests/test_plot_pvalue.py
  sherpa/ui/utils.py
Labels: type:bug, priority:high, area:code, area:c-code

#1261 update to match recent XSPEC model.dat settings
  sherpa/astro/tests/test_astro.py
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/tests/test_xspec.py
Labels: area:tests, area:code, dep:xspec

#1182 Simulations with multiple responses
  docs/_static/evaluation/fake_pha.png
  docs/data/index.rst
  docs/evaluation/astro_background.rst
  docs/evaluation/examples.rst
  docs/evaluation/simulate.rst
  sherpa/astro/all.py
  sherpa/astro/background.py
  sherpa/astro/data.py
  sherpa/astro/fake.py
  sherpa/astro/tests/test_astro_data_notebook.py
  sherpa/astro/tests/test_fake_pha.py
  sherpa/astro/ui/tests/test_astro_ui_utils_simulation.py
  sherpa/astro/ui/utils.py
Labels: type:enhancement, area:science, area:docs, area:tests, area:code
