Repository sherpa/sherpa, pull requests merged in 2021-01, with the labels that each got.

#1043 RTD: install more packages via pip
  docs/environment.yml
Labels: area:docs, priority:high, type:other

#1049 CI: pip submodule test to report coverage
  .github/workflows/ci-pip-workflow.yml
Labels: area:tests

#1004 flake8 F811 - fix repeated test names
  sherpa/astro/io/tests/test_meta.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/optmethods/tests/test_ncoresopt.py
  sherpa/sim/tests/test_sim.py
  sherpa/ui/tests/test_session.py
Labels: area:tests

#1012 Tests: allow test_ui tests to be run with pytest-xdist
  sherpa/ui/tests/test_ui.py
Labels: area:tests

#1018 Fix ShekelModifiedInit missing init par vals
  sherpa/optmethods/tests/test_optmethods.py
  sherpa/optmethods/tests/tstoptfct.hh
Labels: area:tests

#1008 rm warning msgs, fix issue #980
  sherpa/astro/utils/src/_region.cc
Labels: area:code, note: easy review

#1017 reword remark on normalization of Lorentz function
  sherpa/astro/models/__init__.py
Labels: area:docs, note: easy review

#1034 Add contextmanager and docs on how to control the output level of sherpa
  docs/overview/utilities.rst
  sherpa/astro/utils/tests/test_smoke.py
  sherpa/conftest.py
  sherpa/utils/logging.py
  sherpa/utils/tests/test_logging.py
Labels: area:code, area:docs, note: easy review

#1002 Fix error with clobber=False for paging - issue #996
  sherpa/utils/__init__.py
  sherpa/utils/tests/test_utils.py
  sherpa/utils/tests/test_utils_unit.py
Labels: area:code, note: easy review, type:bug

#1039 Add docs for basic.TableModel
  sherpa/models/basic.py
Labels: area:docs, note: easy review

#1000 Improve sherpa.citation (fix #994 #987)
  docs/developer/index.rst
  scripts/make_zenodo_release.py
  sherpa/__init__.py
Labels: area:code, area:docs, type:bug

#1057 Fix plot_source clearwindow setting
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
Labels: area:code, general:visualization, note: easy review, type:bug

#1058 Store the opstr of model combinations (unary and binary)
  sherpa/models/model.py
  sherpa/models/tests/test_model_op.py
Labels: area:code, note: easy review, type:enhancement

#1068 clean up typos in sherpa/plot code
  sherpa/plot/__init__.py
  sherpa/plot/pylab_backend.py
Labels: note: easy review

#1067 Improve testing of sherpa.astro.ui.utils
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/tests/test_astro_ui_utils_simulation.py
  sherpa/astro/ui/tests/test_eqwidth_err.py
  sherpa/conftest.py
  sherpa/sim/tests/test_asymmetric.py
  test_requirements.txt
Labels: area:tests

#1062 Minor code cleanup of sherpa.astro.ui.utils
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/utils.py
Labels: area:code, area:tests

#1016 Jupyter notebook representation not ideal if model components don't have unique names - issue: #1013
  sherpa/models/model.py
  sherpa/models/tests/test_model_notebook.py
Labels: note: easy review, type:bug

#946 Rework stats tests
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/stats/__init__.py
  sherpa/stats/tests/test_stats.py
Labels: area:tests

#1076 sample_flux now uses the id argument
  sherpa/astro/flux.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/utils.py
Labels: area:code, type:bug

#1078 Add error checking for exceptional cases for sample_flux
  sherpa/astro/flux.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/utils.py
Labels: area:code

#1086 Use the logging infrastructure for sample_flux output
  sherpa/astro/flux.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/utils.py
Labels: area:code, type:enhancement
