Repository sherpa/sherpa, pull requests merged in 2022-09, with the labels that each got.

#1567 Fix minor copy and paste error in fake_pha docstring
  sherpa/astro/ui/tests/test_astro_ui_utils_simulation.py
  sherpa/astro/ui/utils.py
Labels: area:docs, note: easy review

#1569 Minor changes to the fake_pha test added in #1567
  sherpa/astro/ui/tests/test_astro_ui_utils_simulation.py
Labels: area:tests

#1572 Tests: fix a logical test error
  sherpa/astro/ui/tests/test_astro_ui_plot.py
Labels: type:bug, priority:high, area:tests, note: easy review

#1574 Avoid occasional test errors from Tcl_AsyncDelete
  sherpa/conftest.py
Labels: area:tests, note: easy review

#1538 Ensure chi2xspecvar errors match XSPEC when 0 counts are present during background subtraction
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/stats/__init__.py
  sherpa/stats/tests/test_stats.py
  sherpa/ui/utils.py
Labels: type:bug, dep:xspec, general:statistics

#1477 Add data validation
  docs/data/index.rst
  docs/developer/index.rst
  docs/examples/simple_interpolation.rst
  docs/model_classes/regrid.rst
  notebooks/ExamplePlots.ipynb
  notebooks/NotebookSupport.ipynb
  notebooks/SherpaQuickStart.ipynb
  sherpa/astro/data.py
  sherpa/astro/instrument.py
  sherpa/astro/io/tests/test_io_pha.py
  sherpa/astro/plot.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_notebook.py
  sherpa/astro/tests/test_astro_instrument.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/tests/test_astro_ui_utils_unit.py
  sherpa/astro/ui/utils.py
  sherpa/astro/utils/__init__.py
  sherpa/astro/utils/tests/test_astro_utils_unit.py
  sherpa/data.py
  sherpa/fit.py
  sherpa/instrument.py
  sherpa/models/regrid.py
  sherpa/models/tests/test_regrid_unit.py
  sherpa/stats/tests/test_stats_unit.py
  sherpa/tests/test_data.py
  sherpa/tests/test_fit_unit.py
  sherpa/tests/test_instrument.py
  sherpa/ui/tests/test_ui.py
  sherpa/ui/tests/test_ui_unit.py
  sherpa/ui/utils.py
  sherpa/utils/err.py
Labels: type:enhancement, area:code, area: grouping

#1585 Tests: work around matplotlib 3.6.0 warning
  sherpa/conftest.py
Labels: area:tests, note: easy review

#1562 report the change in the filter because of calls to notice and ignore
  sherpa/astro/ui/tests/test_astro_session_image.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/tests/test_filtering.py
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code

#1589 Set the language when building the documentation
  docs/conf.py
Labels: area:docs, note: easy review

#1521 Doctestplus
  docs/conf.py
  docs/conftest.py
  docs/developer/index.rst
  docs/evaluation/cache.rst
  docs/evaluation/combine.rst
  docs/evaluation/convolution.rst
  docs/evaluation/examples.rst
  docs/evaluation/integrate.rst
  docs/evaluation/regrid.rst
  docs/evaluation/simulate.rst
  docs/quick.rst
  pytest.ini
  sherpa/astro/data.py
  sherpa/conftest.py
  sherpa/data.py
Labels: type:enhancement, area:docs, area:tests
