Repository sherpa/sherpa, pull requests merged in 2022-04, with the labels that each got.

#1459 Tests: ensure a test is built with a clean UI session
  sherpa/astro/ui/tests/test_astro_ui_unit.py
Labels: area:tests, note: easy review

#1485 get_header_data is an official method of the astro.io backend
  sherpa/astro/io/crates_backend.py
  sherpa/astro/io/dummy_backend.py
  sherpa/astro/io/pyfits_backend.py
Labels: area:code, note: easy review

#1419 Keep .rc file backwards compatible
  sherpa/astro/io/__init__.py
  sherpa/astro/io/tests/test_backend_switch.py
  sherpa/sherpa-standalone.rc
  sherpa/sherpa.rc
Labels: note: easy review

#1328 Versioneer cleanup
  docs/conf.py
  helpers/__init__.py
  helpers/develop.py
  helpers/test.py
  setup.cfg
  setup.py
  sherpa/__init__.py
  sherpa/_version.py
  sherpa/tests/test_sherpa.py
  versioneer.py
Labels: area:build

#1484 Include ciao region patch
  helpers/extensions/__init__.py
  helpers/sherpa_config.py
  setup.cfg
  sherpa/astro/utils/src/_region.cc
Labels: type:enhancement, area:build

#1474 Add basic tests of data validation
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_plot.py
  sherpa/astro/ui/tests/test_astro_ui_io.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/utils/tests/test_astro_utils_unit.py
  sherpa/models/tests/test_regrid.py
  sherpa/models/tests/test_regrid_unit.py
  sherpa/tests/test_data.py
  sherpa/tests/test_fit_unit.py
  sherpa/tests/test_instrument.py
  sherpa/ui/tests/test_ui.py
  sherpa/ui/tests/test_ui_unit.py
Labels: area:tests

#1492 Make tests pass on 3.10
  sherpa/astro/tests/test_astro_data2.py
Labels: note: easy review

#1455 RTD: update the build-from-CIAO documentation
  docs/developer/index.rst
  scripts/use_ciao_config
Labels: area:build, area:docs
