Repository sherpa/sherpa, pull requests merged in 2022-06, with the labels that each got.

#1532 Add plot related tests
  sherpa/astro/ui/tests/test_astro_session.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/plot/tests/test_plot.py
  sherpa/ui/tests/test_session.py
  sherpa/ui/tests/test_ui_plot.py
Labels: area:tests

#1529 Add arguments to -i in sed calls in config script
  scripts/use_ciao_config
Labels: area:build, note: easy review

#1534 docs: fix calc_ftest/mlr documentation
  sherpa/utils/__init__.py
Labels: area:docs, note: easy review

#1536 Tests: add more tests of get_order_plot/plot_order
  sherpa/astro/ui/tests/test_astro_ui_multi_response.py
Labels: area:tests, general:visualization, note: easy review

#1504 CI: rework setup
  .github/scripts/setup_conda.sh
  .github/scripts/setup_ds9.sh
  .github/scripts/setup_xspec.sh
  .github/scripts/setup_xspec_ds9.sh
  .github/scripts/test.sh
  .github/workflows/ci-conda-workflow.yml
  .github/workflows/ci-pip-workflow.yml
Labels: area:build
