Repository sherpa/sherpa, pull requests merged in 2022-12, with the labels that each got.

#1591 Document params and return values for root finding functions
  sherpa/utils/__init__.py
Labels: area:docs, note: easy review

#1621 Fix a cache error with TableModel
  sherpa/models/basic.py
  sherpa/models/tests/test_tablemodel.py
Labels: type:bug, area:code

#1472 tests: remove work-around for #1334 from #1336
  sherpa/models/tests/test_regrid_unit.py
  sherpa/utils/tests/test_utils.py
Labels: area:tests, note: easy review
