Repository sherpa/sherpa, pull requests merged in 2023-10, with the labels that each got.

#1912 Warn when reading in a multi-matrix rmf
  sherpa/astro/io/crates_backend.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/io/tests/test_io_response.py
  sherpa/astro/tests/test_astro_data_rosat_unit.py
  sherpa/astro/tests/test_astro_data_swift_unit.py
  sherpa/astro/ui/utils.py
Labels: type:feature, area:code

#1735 Allow use of the NumPy random generator API
  docs/overview/parallel.rst
  docs/overview/random.rst
  docs/overview/utilities.rst
  docs/overview/utils.rst
  docs/ui/sherpa_astro_ui.rst
  docs/ui/sherpa_ui.rst
  sherpa/astro/data.py
  sherpa/astro/fake.py
  sherpa/astro/flux.py
  sherpa/astro/io/__init__.py
  sherpa/astro/io/crates_backend.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/models/tests/test_astro_model.py
  sherpa/astro/optical/__init__.py
  sherpa/astro/optical/tests/test_optical.py
  sherpa/astro/sim/fullbayes.py
  sherpa/astro/sim/pragbayes.py
  sherpa/astro/sim/tests/test_astro_sim.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_fake_pha.py
  sherpa/astro/ui/tests/test_astro_session.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/tests/test_astro_ui_utils_simulation.py
  sherpa/astro/ui/tests/test_eqwidth_err.py
  sherpa/astro/ui/utils.py
  sherpa/astro/xspec/__init__.py
  sherpa/conftest.py
  sherpa/data.py
  sherpa/image/pyds9_backend.py
  sherpa/io.py
  sherpa/models/model.py
  sherpa/models/parameter.py
  sherpa/models/tests/test_basic.py
  sherpa/models/tests/test_parameter.py
  sherpa/models/tests/test_regrid.py
  sherpa/optmethods/ncoresde.py
  sherpa/optmethods/opt.py
  sherpa/optmethods/optfcts.py
  sherpa/optmethods/tests/test_opt_original.py
  sherpa/optmethods/tests/test_opt_unit.py
  sherpa/plot/__init__.py
  sherpa/sim/__init__.py
  sherpa/sim/mh.py
  sherpa/sim/sample.py
  sherpa/sim/simulate.py
  sherpa/sim/tests/test_asymmetric.py
  sherpa/sim/tests/test_sim.py
  sherpa/ui/tests/test_plot_pvalue.py
  sherpa/ui/tests/test_ui.py
  sherpa/ui/utils.py
  sherpa/utils/__init__.py
  sherpa/utils/numeric_types.py
  sherpa/utils/parallel.py
  sherpa/utils/random.py
  sherpa/utils/tests/test_parallel.py
  sherpa/utils/tests/test_random.py
  sherpa/utils/tests/test_utils.py
Labels: type:enhancement, area:code, CI arch

#1899 Bokeh_class
  .github/workflows/ci-pip-workflow.yml
  docs/conf.py
  docs/environment.yml
  docs/indices.rst
  docs/plots/bokeh_backend.rst
  docs/plots/index.rst
  docs/plots/testing.rst
  pytest.ini
  sherpa/astro/tests/test_astro_data_notebook.py
  sherpa/conftest.py
  sherpa/plot/__init__.py
  sherpa/plot/backends.py
  sherpa/plot/bokeh_backend.py
  sherpa/plot/pylab_backend.py
  sherpa/plot/testing.py
  sherpa/plot/tests/test_plot_notebook.py
  sherpa/plot/utils.py
  sherpa/tests/test_data_notebook.py
Labels: general:visualization
