Repository sherpa/sherpa, pull requests merged in 2023-09, with the labels that each got.

#1841 Minor refresh of AstroPy I/O code for better FITS and ASCII output
  sherpa/astro/io/__init__.py
  sherpa/astro/io/crates_backend.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/io/tests/test_io.py
  sherpa/astro/io/tests/test_io_pha.py
  sherpa/astro/ui/tests/test_astro_session.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
Labels: area:code

#1877 un-whitelist deprecation warnings
  sherpa/conftest.py
Labels: area:tests, note: easy review

#1878 Tests: better handle case where both astropy and crates are available
  sherpa/astro/ui/tests/test_astro_session.py
Labels: area:tests, note: easy review

#1883 Update setup_ds9.sh for DS9 8.5
  .github/scripts/setup_ds9.sh
Labels: priority:blocker, area:tests

#1839 ui: add get_plot_prefs/get_contour_prefs calls
  docs/ui/sherpa_astro_ui.rst
  docs/ui/sherpa_ui.rst
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code, general:visualization, note:needs SDS testing

#1853 XSPEC: update model parameters to match XSPEC 12.13.1 / HEASOFT 6.32
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/tests/test_xspec_unit.py
Labels: dep:xspec

#1888 UI: set_analysis reports the filter change - fix #1590
  sherpa/astro/ui/tests/test_astro_session.py
  sherpa/astro/ui/tests/test_filtering.py
  sherpa/astro/ui/utils.py
Labels: type:enhancement, area:code

#1382 Plot changes: Step 1 A- Draft API for backend classes
  docs/conf.py
  docs/overview/testing.rst
  docs/plots/backend_utils.rst
  docs/plots/backends.rst
  docs/plots/basebackends.rst
  docs/plots/index.rst
  docs/plots/plot.rst
  docs/plots/pylab_area_backend.rst
  docs/plots/pylab_backend.rst
  docs/ui/sherpa_astro_ui.rst
  docs/ui/sherpa_ui.rst
  pytest.ini
  sherpa/astro/data.py
  sherpa/astro/plot.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_notebook.py
  sherpa/astro/tests/test_astro_plot.py
  sherpa/astro/ui/tests/test_astro_ui_fluxes.py
  sherpa/astro/ui/tests/test_astro_ui_multi_response.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/tests/test_session_copy.py
  sherpa/astro/ui/utils.py
  sherpa/conftest.py
  sherpa/plot/__init__.py
  sherpa/plot/backend_utils.py
  sherpa/plot/backends.py
  sherpa/plot/dummy_backend.py
  sherpa/plot/pylab_area_backend.py
  sherpa/plot/pylab_backend.py
  sherpa/plot/tests/test_backend.py
  sherpa/plot/tests/test_backend_utils.py
  sherpa/plot/tests/test_plot.py
  sherpa/plot/tests/test_plot_notebook.py
  sherpa/plot/tests/test_plot_warnings.py
  sherpa/plot/tests/test_pylab_specific.py
  sherpa/sherpa-standalone.rc
  sherpa/tests/test_data_notebook.py
  sherpa/ui/tests/test_plot_pvalue.py
  sherpa/ui/tests/test_session.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
  sherpa/utils/__init__.py
  sherpa/utils/err.py
  sherpa/utils/testing.py
  sherpa/utils/tests/test_utils_error_unit.py
Labels: dep:matplotlib, general:visualization

#1653 Allow arbitrary functions for linking parameters
  docs/model_classes/usermodel.rst
  docs/models/index.rst
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/models/parameter.py
  sherpa/models/tests/test_parameter.py
Labels: type:enhancement

#1824 remove non-existent datastack plotting backend initialization attribute
  sherpa/astro/datastack/utils.py
Labels: type:bug, area:code, general:visualization

#1738 Return more-useful information when an XSPEC model fails
  sherpa/astro/xspec/__init__.py
  sherpa/include/sherpa/astro/xspec_extension.hh
Labels: type:enhancement, area:code, dep:xspec, area:c-code

#1836 Allow ARF and RMF to be written out
  docs/overview/astro_io.rst
  docs/ui/sherpa_astro_ui.rst
  sherpa/astro/instrument.py
  sherpa/astro/io/__init__.py
  sherpa/astro/io/crates_backend.py
  sherpa/astro/io/dummy_backend.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/io/tests/test_io_img.py
  sherpa/astro/io/tests/test_io_pha.py
  sherpa/astro/io/tests/test_io_response.py
  sherpa/astro/tests/test_astro_instrument.py
  sherpa/astro/ui/tests/test_astro_ui_io.py
  sherpa/astro/ui/utils.py
Labels: type:enhancement, area:code

#1730 Update xspec model creation
  docs/developer/index.rst
  sherpa/astro/utils/tests/test_astro_utils_xspec.py
  sherpa/astro/utils/xspec.py
Labels: type:enhancement, area:code, dep:xspec

#1904 Upgrade base image for aarch64 testing
  .github/workflows/ci-pip-arch.yml
Labels: area:tests, CI arch

#1892 data: group backgrounds before source - fix #1881
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
Labels: type:bug, priority:medium, area:code

#1890 Convert a RMF to an image
  .gitignore
  docs/index.rst
  docs/model_classes/astro_instrument.rst
  notebooks/ViewingPHAResponses.ipynb
  notebooks/nbmapping.dat
  sherpa/astro/data.py
  sherpa/astro/instrument.py
  sherpa/astro/io/__init__.py
  sherpa/astro/tests/test_astro_instrument.py
Labels: type:enhancement, area:code, general:visualization

#1855 group_counts et al now default to using the existing mask as the tabstops, unless explicitly given
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/tests/test_astro_ui_utils_unit.py
  sherpa/astro/ui/utils.py
Labels: type:enhancement, area:code, note:needs SDS testing, area: grouping

#1891 ui: add calc_bkg_stat - fix #333
  docs/ui/sherpa_astro_ui.rst
  sherpa/astro/ui/tests/test_astro_ui_background.py
  sherpa/astro/ui/utils.py
  sherpa/fit.py
Labels: type:enhancement, area:code

#1908 Add versionadded note to set_plot_backend
  sherpa/ui/utils.py
Labels: area:docs, note: easy review

#1906 Remove hardcoded matplotlib for _repr_html_ of RMF and DataImage2D
  docs/plots/astroplot.rst
  docs/plots/plot.rst
  notebooks/ExamplePlots.ipynb
  sherpa/astro/data.py
  sherpa/astro/plot.py
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/astro/ui/utils.py
  sherpa/plot/__init__.py
  sherpa/plot/backends.py
  sherpa/plot/pylab_backend.py
Labels: type:enhancement, area:code, general:visualization

#1909 Add security warnings to restore functions
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
Labels: area:other, note: easy review

#1874 save_all improvements for set_psf and load_xstable_model
  sherpa/astro/io/tests/test_io_img.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/ui/serialize.py
  sherpa/astro/ui/tests/test_astro_session.py
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/astro/ui/utils.py
Labels: type:bug, type:enhancement, area:code

#1861 Allow XSPEC table models to be created and written out
  docs/overview/astro_io.rst
  docs/overview/astro_io_xstable.rst
  docs/overview/utilities.rst
  sherpa/astro/io/crates_backend.py
  sherpa/astro/io/dummy_backend.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/io/tests/test_io_xspec_table_model.py
  sherpa/astro/io/xstable.py
Labels: type:enhancement, area:code, dep:xspec

#1911 IO: add missing import for pyfits backend
  sherpa/astro/io/pyfits_backend.py
Labels: type:bug, area:code, note: easy review
