Repository sherpa/sherpa, pull requests merged in 2024-09, with the labels that each got.

#2111 IO: ensure NUMELT/GRP are written out as integers for RMF header
  sherpa/astro/io/__init__.py
Labels: type:bug, area:code, note: easy review

#2120 Improve handling of STAT/SYS_ERR PHA columns
  sherpa/astro/io/__init__.py
  sherpa/astro/tests/test_astro_data_asca_unit.py
  sherpa/astro/tests/test_astro_data_chandra_unit.py
  sherpa/astro/tests/test_astro_data_rosat_unit.py
  sherpa/astro/tests/test_astro_data_swift_unit.py
  sherpa/astro/tests/test_astro_data_xmm_unit.py
Labels: type:bug, area:code

#2124 Improve the documentation of the id/bkg_id/resp_id arguments
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
Labels: area:docs, area:code

#2115 doc: add examples of using set_xlabel/ylabel
  docs/_static/ui/session_basic_example_fit.png
  docs/ui/index.rst
  notebooks/ExamplePlots.ipynb
Labels: area:docs

#2125 Allow per plot kwargs for plot_xxx_components calls
  sherpa/plot/__init__.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
  sherpa/utils/__init__.py
Labels: type:enhancement, area:code, general:visualization

#2121 UI: add calc_model/source commands
  docs/ui/sherpa_astro_ui.rst
  sherpa/astro/ui/tests/test_astro_ui_utils_unit.py
  sherpa/astro/ui/utils.py
Labels: type:enhancement, area:code, note:needs SDS testing

#2123 Data cleanups
  sherpa/astro/data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/data.py
  sherpa/utils/__init__.py
Labels: area:code

#2130 data: fixup numpy import
  sherpa/astro/data.py
Labels: area:code, note: easy review

#2108 Asymmetric settings
  sherpa/astro/ui/utils.py
  sherpa/sim/__init__.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code

#2133 UI: add format and delim arguments to get_filter. Fix #1277
  sherpa/astro/ui/tests/test_filtering.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code, note: easy review

#1757 Allow the wstat statistic to be used in the liklihood-ratio test
  sherpa/plot/__init__.py
  sherpa/sim/simulate.py
  sherpa/sim/tests/test_sim.py
  sherpa/sim/tests/test_sim_unit.py
  sherpa/ui/tests/test_plot_pvalue.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code

#2137 Fix doctests in `sherpa.plot.__init__`
  sherpa/plot/__init__.py
Labels: area:docs, note: easy review

#2126 Allow plot and contour to change the plot layout and have per-plot settings.
  sherpa/plot/__init__.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code, general:visualization

#2129 Fix plot overplot
  sherpa/astro/ui/utils.py
  sherpa/plot/__init__.py
  sherpa/ui/tests/test_ui_plot.py
  sherpa/ui/utils.py
Labels: type:bug, area:code, general:visualization

#2139 Update helpdesk URL
  docs/bugs.rst
Labels: area:docs, note: easy review

#2140 Updated docs for asymmetric errors
  sherpa/astro/ui/utils.py
Labels: area:docs, note: easy review

#2138 UI: add documentation for table to show_xsabund
  sherpa/astro/ui/tests/test_astro_ui_utils_unit.py
  sherpa/astro/ui/utils.py
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/src/_xspec.cc
  sherpa/astro/xspec/tests/test_xspec_unit.py
Labels: type:enhancement, area:code, area:c-code

#2141 Update LaTeX labels and docs for bokeh
  docs/plots/backends.rst
  docs/plots/bokeh_backend.rst
  docs/plots/index.rst
  pytest.ini
  sherpa/astro/ui/tests/test_astro_ui_plot.py
  sherpa/plot/bokeh_backend.py
Labels: general:visualization, note: easy review

#2118 Improve support for PHA data starting at channel 0
  sherpa/astro/data.py
  sherpa/astro/instrument.py
  sherpa/astro/io/__init__.py
  sherpa/astro/io/tests/test_io_pha.py
  sherpa/astro/io/tests/test_io_response.py
  sherpa/astro/tests/test_astro.py
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_asca_unit.py
  sherpa/astro/tests/test_astro_data_swift_unit.py
  sherpa/astro/tests/test_astro_data_xmm_unit.py
  sherpa/astro/tests/test_astro_instrument.py
  sherpa/astro/ui/tests/test_astro_ui.py
  sherpa/astro/ui/utils.py
  sherpa/astro/utils/tests/test_astro_utils_unit.py
  sherpa/include/sherpa/astro/utils.hh
Labels: type:bug, area:code, area:c-code

#2152 DATA: clean up DataPHA.get_x
  sherpa/astro/data.py
Labels: area:code

#1949 Initial support for Python 3.12
  .github/scripts/setup_conda.sh
  .github/workflows/ci-conda-workflow.yml
  .github/workflows/ci-pip-arch.yml
  .github/workflows/ci-pip-workflow.yml
  MANIFEST.in
  README.md
  docs/index.rst
  docs/install.rst
  helpers/__init__.py
  helpers/build.py
  helpers/develop.py
  helpers/extensions/__init__.py
  helpers/sdist.py
  helpers/sherpa_config.py
  pyproject.toml
  recipes/conda/build.sh
  recipes/conda/meta.yaml
  setup.cfg
  setup.py
Labels: area:build

#2157 Improve test coverage of ignore_bad
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/ui/tests/test_astro_ui_unit.py
  sherpa/astro/ui/tests/test_filtering.py
  sherpa/astro/utils/tests/test_astro_utils_unit.py
Labels: area:tests

#2160 Fixup test failures from #2118
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/io/tests/test_io_pha.py
Labels: type:bug, priority:blocker, area:tests, area:code

#2161 UI: note when a 1D filter command has failed
  sherpa/astro/ui/tests/test_filtering.py
  sherpa/ui/utils.py
Labels: type:enhancement, area:code

#2162 TEST: ignore fork deprecation warnings
  sherpa/conftest.py
Labels: area:tests
