Repository sherpa/sherpa, pull requests merged in 2025-07, with the labels that each got.

#2321 Minor simplification of the extension code
  sherpa/astro/models/src/_modelfcts.cc
  sherpa/astro/utils/src/_pileup.cc
  sherpa/astro/utils/src/_utils.cc
  sherpa/astro/utils/src/_wcs.cc
  sherpa/estmethods/src/estwrappers.cc
  sherpa/include/sherpa/extension.hh
  sherpa/models/src/_modelfcts.cc
  sherpa/stats/src/_statfcts.cc
  sherpa/utils/src/_psf.cc
  sherpa/utils/src/_utils.cc
  sherpa/utils/src/integration.cc
Labels: area:build, area:c-code

#2325 Update docstring for get_xsabundances
  sherpa/astro/xspec/__init__.py
Labels: area:docs, note: easy review

#2278 Use `modelCacher1D` (now aliased to `modelCacher`) for 2D models
  docs/evaluation/cache.rst
  docs/model_classes/model.rst
  sherpa/astro/models/__init__.py
  sherpa/models/basic.py
  sherpa/models/model.py
  sherpa/models/tests/test_caching.py
Labels: type:enhancement, general:optimisation

#2259 Add typing statements to the optimization code
  sherpa/estmethods/__init__.py
  sherpa/fit.py
  sherpa/optmethods/__init__.py
  sherpa/optmethods/ncoresde.py
  sherpa/optmethods/ncoresnm.py
  sherpa/optmethods/opt.py
  sherpa/optmethods/optfcts.py
  sherpa/optmethods/tests/test_ncoresopt.py
  sherpa/optmethods/tests/test_opt_original.py
  sherpa/stats/__init__.py
  sherpa/utils/parallel.py
  sherpa/utils/random.py
  sherpa/utils/types.py
Labels: area:code
