Repository sherpa/sherpa, pull requests merged in 2025-04, with the labels that each got.

#2261 Add tests related to analysis setting
  sherpa/astro/tests/test_astro_data.py
  sherpa/astro/tests/test_astro_data2.py
  sherpa/astro/tests/test_astro_data_xmm_unit.py
Labels: area:tests

#2256 Faster hash for modelCacher1D
  sherpa/models/model.py
  sherpa/models/tests/test_model.py
Labels: note: easy review

#2252 Allow Sherpa to build against XSPEC 12.15.0
  docs/developer/index.rst
  docs/indices.rst
  docs/install.rst
  docs/model_classes/astro_xspec.rst
  helpers/xspec_config.py
  scripts/add_xspec_model.py
  scripts/update_xspec_docs.py
  scripts/update_xspec_functions.py
  sherpa/astro/ui/tests/test_serialize.py
  sherpa/astro/utils/tests/test_astro_utils_xspec.py
  sherpa/astro/utils/xspec.py
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/src/_xspec.cc
  sherpa/astro/xspec/tests/test_xspec.py
  sherpa/astro/xspec/tests/test_xspec_con.py
  sherpa/conftest.py
Labels: type:enhancement, area:build, area:docs, area:code, dep:xspec, area:c-code

#2273 Make sure all datastack-wrapped functions are added to namespace
  sherpa/astro/datastack/__init__.py
  sherpa/astro/datastack/tests/test_datastack.py
  sherpa/astro/datastack/utils.py
  sherpa/utils/__init__.py
Labels: note: easy review

#2279 Note support for Python 3.13
  README.md
  docs/index.rst
  docs/install.rst
  pyproject.toml
Labels: area:build, area:docs, note: easy review

#2287 Use python 3.10 syntax for typing for the ui modules
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
  sherpa/utils/__init__.py
Labels: area:code

#2274 Set `cache=0` by default for models that are fast to calculate
  docs/developer/index.rst
  docs/evaluation/cache.rst
  sherpa/astro/models/__init__.py
  sherpa/astro/models/tests/test_astro_model.py
  sherpa/astro/models/tests/test_astro_model_cache.py
  sherpa/astro/optical/__init__.py
  sherpa/astro/optical/tests/test_optical_model_cache.py
  sherpa/astro/xspec/__init__.py
  sherpa/astro/xspec/tests/test_xspec_caching_performance.py
  sherpa/conftest.py
  sherpa/models/basic.py
  sherpa/models/tests/test_basic_cache.py
  sherpa/models/tests/test_model.py
Labels: general:optimisation

#2280 Add option `record_steps` to `Fit.fit()` calls
  pytest.ini
  sherpa/astro/ui/utils.py
  sherpa/fit.py
  sherpa/tests/test_fit_unit.py
  sherpa/ui/utils.py
Labels: type:feature, general:statistics, general:optimisation, general:visualization

#2288 ui: add more examples of using SherpaVerbosity
  sherpa/astro/ui/utils.py
  sherpa/ui/utils.py
Labels: area:docs, note: easy review

#2286 Add an interface to ArviZ
  .github/workflows/ci-pip-workflow.yml
  docs/_static/mcmc/mcmc_cdf_xpos.png
  docs/_static/mcmc/mcmc_covar_matrix.png
  docs/_static/mcmc/mcmc_pdf_xpos.png
  docs/_static/mcmc/mcmc_scatter_r0_alpha.png
  docs/_static/mcmc/mcmc_scatter_r0_alpha_compare.png
  docs/_static/mcmc/mcmc_sim.png
  docs/_static/mcmc/mcmc_trace_r0.png
  docs/_static/mcmc/mcmc_trace_r0_manual.png
  docs/conf.py
  docs/environment.yml
  docs/install.rst
  docs/mcmc/index.rst
  docs/mcmc/sim.rst
  pyproject.toml
  pytest.ini
  sherpa/sim/__init__.py
  sherpa/sim/tests/test_sim.py
Labels: type:enhancement, general:statistics

#2289 Update http -> https
  CITATION
  CONTRIBUTING.md
  COPYRIGHT
  README.md
  docs/conf.py
  docs/developer/index.rst
  docs/install.rst
  docs/mcmc/index.rst
  recipes/conda/meta.yaml
  sherpa/__init__.py
  sherpa/astro/datastack/__init__.py
  sherpa/astro/io/pyfits_backend.py
  sherpa/astro/models/__init__.py
  sherpa/astro/optical/__init__.py
  sherpa/astro/sim/__init__.py
  sherpa/astro/ui/serialize.py
  sherpa/astro/utils/__init__.py
  sherpa/astro/utils/xspec.py
  sherpa/fit.py
  sherpa/image/DS9.py
  sherpa/models/basic.py
  sherpa/models/regrid.py
  sherpa/optmethods/__init__.py
  sherpa/optmethods/optfcts.py
  sherpa/sim/__init__.py
  sherpa/sim/mh.py
  sherpa/sim/simulate.py
  sherpa/stats/__init__.py
  sherpa/stats/tests/test_user_stat.py
  sherpa/utils/__init__.py
  sherpa/utils/akima.py
Labels: area:docs, note: easy review
